<?php
// Автоматично згенерована карта всіх зображень сайту, доступних для заміни в адмінці.
// Формат: 'slug' => ['path' => відносний шлях у кожній копії сайту, 'label' => назва, 'cat' => категорія]
return [
    // ---- Логотипи та іконка сайту ----
    'logo' => ['path' => 'src/img/logo.png', 'label' => 'Логотип у шапці сайту', 'cat' => 'logo'],
    'logo_big' => ['path' => 'src/img/logo-2.png', 'label' => 'Великий логотип на банері', 'cat' => 'logo'],
    'favicon' => ['path' => 'src/img/logo-3.png', 'label' => 'Іконка сайту у вкладці браузера (favicon)', 'cat' => 'logo'],
    // ---- Таблиця цін ----
    'price_table' => ['path' => 'src/img/price-table.jpg', 'label' => 'Таблиця цін', 'cat' => 'prices'],
    // ---- Банер і фони розділів ----
    'bg_banner' => ['path' => 'src/img/banner.jpg', 'label' => 'Фон банера на головному екрані', 'cat' => 'banners'],
    'bg_about' => ['path' => 'src/img/about-us-bg.jpg', 'label' => 'Фон блоку «Про нас»', 'cat' => 'banners'],
    'bg_how_we_work' => ['path' => 'src/img/how-we-work-bg.jpg', 'label' => 'Фон блоку «Як ми працюємо»', 'cat' => 'banners'],
    'bg_dry_cleaning' => ['path' => 'src/img/dry-cleaning-bg.png', 'label' => 'Фон блоку хімчистки', 'cat' => 'banners'],
    // ---- Фото робіт і команди ----
    'photo_carwash' => ['path' => 'src/img/carwash.png', 'label' => 'Ілюстрація миття авто', 'cat' => 'work_photos'],
    'photo_detailing_steps' => ['path' => 'src/img/detailing-steps.jpg', 'label' => 'Інфографіка «8 етапів хімчистки»', 'cat' => 'work_photos'],
    'icon_chemistry' => ['path' => 'src/img/we-use-1.png', 'label' => 'Значок «професійна хімія»', 'cat' => 'work_photos'],
    'icon_equipment' => ['path' => 'src/img/karch-img.jpg', 'label' => 'Значок «професійне обладнання»', 'cat' => 'work_photos'],
    'icon_staff' => ['path' => 'src/img/workers-icon.jpg', 'label' => 'Значок «наші працівники»', 'cat' => 'work_photos'],
    'badge_lviv' => ['path' => 'src/img/lviv-logo.png', 'label' => 'Значок міста Львів', 'cat' => 'work_photos'],
    'wrk_1' => ['path' => 'src/img/wrk/wrk_1.png', 'label' => 'Фото працівника 1', 'cat' => 'work_photos'],
    'wrk_2' => ['path' => 'src/img/wrk/wrk_2.png', 'label' => 'Фото працівника 2', 'cat' => 'work_photos'],
    'wrk_3' => ['path' => 'src/img/wrk/wrk_4.png', 'label' => 'Фото працівника 3', 'cat' => 'work_photos'],
    'wrk_4' => ['path' => 'src/img/wrk/wrk_5.png', 'label' => 'Фото працівника 4', 'cat' => 'work_photos'],
    'wrk_5' => ['path' => 'src/img/wrk/wrk_6.png', 'label' => 'Фото працівника 5', 'cat' => 'work_photos'],
    // ---- Логотипи клієнтів ----
    'client_antoshka' => ['path' => 'src/img/clients/antoshka-logo.jpg', 'label' => 'Антошка', 'cat' => 'clients'],
    'client_astoria' => ['path' => 'src/img/clients/astoria-logo.png', 'label' => 'Astoria', 'cat' => 'clients'],
    'client_avalon' => ['path' => 'src/img/clients/avalon-logo.png', 'label' => 'Avalon', 'cat' => 'clients'],
    'client_brocard' => ['path' => 'src/img/clients/brocard-logo.jpg', 'label' => 'Brocard', 'cat' => 'clients'],
    'client_dnister' => ['path' => 'src/img/clients/dnister-logo.jpg', 'label' => 'Дністер', 'cat' => 'clients'],
    'client_fash' => ['path' => 'src/img/clients/fash-logo.png', 'label' => 'FASH', 'cat' => 'clients'],
    'client_foxtrot' => ['path' => 'src/img/clients/foxtrot-logo.jpg', 'label' => 'Фокстрот', 'cat' => 'clients'],
    'client_kyivstar' => ['path' => 'src/img/clients/kyivstar-logo.jpg', 'label' => 'Київстар', 'cat' => 'clients'],
    'client_lviv' => ['path' => 'src/img/clients/lviv-logo.jpg', 'label' => 'Львів (місто)', 'cat' => 'clients'],
    'client_lvivske' => ['path' => 'src/img/clients/lvivske-logo.gif', 'label' => 'Львівське', 'cat' => 'clients'],
    'client_mark' => ['path' => 'src/img/clients/mark-logo.png', 'label' => 'Mark', 'cat' => 'clients'],
    'client_mercedes' => ['path' => 'src/img/clients/mercedes-benz-logo.jpg', 'label' => 'Mercedes-Benz', 'cat' => 'clients'],
    'client_metro' => ['path' => 'src/img/clients/metro-logo.jpg', 'label' => 'METRO', 'cat' => 'clients'],
    'client_pizzacelentano' => ['path' => 'src/img/clients/pizzacelentano-logo.jpg', 'label' => 'Pizza Celentano', 'cat' => 'clients'],
    'client_pliag' => ['path' => 'src/img/clients/pliag-logo.jpg', 'label' => 'Pliag', 'cat' => 'clients'],
    'client_riel' => ['path' => 'src/img/clients/riel-logo.jpg', 'label' => 'Riel', 'cat' => 'clients'],
    'client_turkish' => ['path' => 'src/img/clients/turkish-airlines-logo.jpg', 'label' => 'Turkish Airlines', 'cat' => 'clients'],
    'client_victoria' => ['path' => 'src/img/clients/victoria-gardens-logo.jpg', 'label' => 'Victoria Gardens', 'cat' => 'clients'],
    'client_yaponakhata' => ['path' => 'src/img/clients/yaponakhata-logo.jpg', 'label' => 'Японахата', 'cat' => 'clients'],
    // ---- Фото відгуків ----
    'review_1' => ['path' => 'src/img/reviews/review-1.jpg', 'label' => 'Відгук 1', 'cat' => 'reviews'],
    'review_2' => ['path' => 'src/img/reviews/review-2.jpg', 'label' => 'Відгук 2', 'cat' => 'reviews'],
    'review_3' => ['path' => 'src/img/reviews/review-3.jpg', 'label' => 'Відгук 3', 'cat' => 'reviews'],
    'review_4' => ['path' => 'src/img/reviews/review-4.jpg', 'label' => 'Відгук 4', 'cat' => 'reviews'],
    'review_5' => ['path' => 'src/img/reviews/review-5.jpg', 'label' => 'Відгук 5', 'cat' => 'reviews'],
    'review_6' => ['path' => 'src/img/reviews/review-6.jpg', 'label' => 'Відгук 6', 'cat' => 'reviews'],
    'review_7' => ['path' => 'src/img/reviews/review-7.jpg', 'label' => 'Відгук 7', 'cat' => 'reviews'],
    'review_8' => ['path' => 'src/img/reviews/review-8.jpg', 'label' => 'Відгук 8', 'cat' => 'reviews'],
    // ---- Значки соцмереж і зв'язку ----
    'icon_instagram' => ['path' => 'src/img/instagram-icon.png', 'label' => 'Значок Instagram', 'cat' => 'social'],
    'icon_viber' => ['path' => 'src/img/viber-icon.png', 'label' => 'Значок Viber', 'cat' => 'social'],
    'icon_kyivstar_phone' => ['path' => 'src/img/kyivstar-icon.png', 'label' => 'Значок оператора (Київстар)', 'cat' => 'social'],
    // ---- Логотипи брендів хімії й обладнання ----
    'brand_carpro' => ['path' => 'src/img/carpro-logo.png', 'label' => 'CarPro', 'cat' => 'brands'],
    'brand_karcher' => ['path' => 'src/img/karcher-logo.jpg', 'label' => 'Karcher', 'cat' => 'brands'],
    'brand_kenotek' => ['path' => 'src/img/kenotek-logo.jpg', 'label' => 'Kenotek', 'cat' => 'brands'],
    'brand_nanolex' => ['path' => 'src/img/nanolex-logo.png', 'label' => 'Nanolex', 'cat' => 'brands'],
    'brand_rupes' => ['path' => 'src/img/rupes-logo.png', 'label' => 'Rupes', 'cat' => 'brands'],
    // ---- Дрібні іконки інтерфейсу ----
    'icon_carousel_arrow' => ['path' => 'src/img/carousel-arow.png', 'label' => 'Стрілка каруселі відгуків', 'cat' => 'ui_icons'],
    'icon_is' => ['path' => 'src/img/is-icon.png', 'label' => 'Значок «так» (порівняння)', 'cat' => 'ui_icons'],
    'icon_isnt' => ['path' => 'src/img/isnt-icon.png', 'label' => 'Значок «ні» (порівняння)', 'cat' => 'ui_icons'],
    'icon_service_1' => ['path' => 'src/img/service-1.png', 'label' => 'Значок послуги 1', 'cat' => 'ui_icons'],
    'icon_service_2' => ['path' => 'src/img/service-2.png', 'label' => 'Значок послуги 2', 'cat' => 'ui_icons'],
    'icon_why_1' => ['path' => 'src/img/why-we-icon-1.png', 'label' => 'Значок «чому ми» 1', 'cat' => 'ui_icons'],
    'icon_why_2' => ['path' => 'src/img/why-we-icon-2.png', 'label' => 'Значок «чому ми» 2', 'cat' => 'ui_icons'],
    'icon_why_3' => ['path' => 'src/img/why-we-icon-3.jpg', 'label' => 'Значок «чому ми» 3', 'cat' => 'ui_icons'],
    'icon_why_4' => ['path' => 'src/img/why-we-icon-4.jpg', 'label' => 'Значок «чому ми» 4', 'cat' => 'ui_icons'],
    'icon_why_5' => ['path' => 'src/img/why-we-icon-5.png', 'label' => 'Значок «чому ми» 5', 'cat' => 'ui_icons'],
    'icon_why_6' => ['path' => 'src/img/why-we-icon-6.png', 'label' => 'Значок «чому ми» 6', 'cat' => 'ui_icons'],
];
